### ISSUE TITLE
To-Do's week of 2/14

### ISSUE THREAD

**Issue by EricGalluzzi** [EricGalluzzi/Mosquito#5]
- [x] Weather Interface on Front End
- [x] Write Script/introduce at meeting
- [x] Find datasets/information on testing
- [ ] Delineate testing sites and request any necessary geospatial data
- [x] Push new Graph Interface
