### ISSUE TITLE
Final eh week To-Do's

### ISSUE THREAD

**Issue by EricGalluzzi** [EricGalluzzi/Mosquito#6]
- [ ] refactor queries on mongoDB website handler
- [ ] set up boujee flask with makeshift algorithm
- [ ] somehow find an equation for SMER->GWC
